# NNFL Python Tutorial

Adapted from the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

Python is a high-level, interpreted and dynamically-typed language. Each Operation comes with a small type-checking overhead and with many repeated small operations (ex. in a loop), this overhead becomes significant. So in a way what makes python fast for development is what makes it slow for execution.

## Numpy

Numpy is designed to help us get the best of both the parts (fast development and execution time) by pushing repeated operations into a statically-typed compiled layer. Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

Important Topics:
* Array indexing and slicing
* Aggregation Functions
* Matrix Operations
* Reshaping
* Broadcasting


To use Numpy, we first need to import the `numpy` package:

In [1]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.dtype)            # Element data type
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<type 'numpy.ndarray'>
int64
(3,)
(1, 2, 3)
[5 2 3]


In [3]:
a = [1,2,3,8,3,8,1,6]
b = [x + 10 for x in a]
b

[11, 12, 13, 18, 13, 18, 11, 16]

In [4]:
a= np.array(a)
b = a + 10
b

array([11, 12, 13, 18, 13, 18, 11, 16])

In [5]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"   

(2, 3)
(1, 2, 4)


Numpy also provides many functions to create arrays:

In [7]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[ 0.  0.]
 [ 0.  0.]]


In [8]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[ 1.  1.]]


In [9]:
c = np.full((2,2), 7, dtype='float64')  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[ 7.  7.]
 [ 7.  7.]]


In [10]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[ 1.  0.]
 [ 0.  1.]]


In [11]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[ 0.47114045  0.72697175]
 [ 0.38416264  0.28290911]]


In [12]:
f = np.random.randint(1,10, (2,2))  # Create an array filled with random int values between 1(inclusive) and 10
print(f)                            # Might print "[[ 5  8]
                                    #               [ 2  1]]"

[[2 1]
 [8 4]]


### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

### Submatrix

In [13]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [14]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a)   # Prints "77"

2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Indexing Specific Rows and Columns

In [15]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [16]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

(array([5, 6, 7, 8]), (4,))
(array([[5, 6, 7, 8]]), (1, 4))


In [17]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

(array([ 2,  6, 10]), (3,))
(array([[ 2],
       [ 6],
       [10]]), (3, 1))


### Integer Indexing

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [18]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# An example of integer array indexing.
# The returned array will have shape (3,) and
print("")
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
print("")
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]

[1 4 5]


In [19]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [20]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [22]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [23]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(a)
print(bool_idx)     


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [24]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"
print("")
# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"
print("")
a[a>3]= 0
print(a)

[3 4 5 6]

[3 4 5 6]

[[1 2]
 [3 0]
 [0 0]]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [25]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int32)   # Force a particular datatype
print(x.dtype)                         # Prints "int32"

int64
float64
int32


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [26]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [27]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [28]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [29]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [30]:
print(x)
print(1.0/x)

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.          0.5       ]
 [ 0.33333333  0.25      ]]


In [31]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [32]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print("v:"+" shape: "+ str(v.shape))
print(v)
print("\nw:"+" shape: "+ str(w.shape))
print(w)
print("\nDot Product")
print(v.dot(w))
print(np.dot(v, w))

v: shape: (2,)
[ 9 10]

w: shape: (2,)
[11 12]

Dot Product
219
219


In [33]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print("x:"+" shape: "+ str(x.shape))
print(x)
print("\nv:"+" shape: "+ str(v.shape))
print(v)
print("\nDot")
print(x.dot(v))
print("\nElementWise")
print(x*v)

x: shape: (2, 2)
[[1 2]
 [3 4]]

v: shape: (2,)
[ 9 10]

Dot
[29 67]

ElementWise
[[ 9 20]
 [27 40]]


In [34]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

<img src="files/images/axis.jpg" alt="Drawing" style="width: 500px;" >

In [35]:
import numpy as np

# Sum Function

x = np.array([[1,2],[3,4]])
print("x:"+" shape: "+ str(x.shape))
print(x)

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

x: shape: (2, 2)
[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [36]:

x = np.array([[1,2],[3,4]])
print("x:"+" shape: "+ str(x.shape))
print(x)
print("")
print(np.max(x))  # Compute sum of all elements; prints "10"
print(np.max(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.max(x, axis=1))  # Compute sum of each row; prints "[3 7]"
print(np.argmax(x, axis=0))

x: shape: (2, 2)
[[1 2]
 [3 4]]

4
[3 4]
[2 4]
[1 1]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [37]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [38]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"


[1 2 3]
[1 2 3]


In [39]:
v = v.reshape(3,1)
print(v)
v = v.reshape(1,3)
print(v)

[[1]
 [2]
 [3]]
[[1 2 3]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

<img src="files/images/broadcast.png" alt="Drawing" style="width: 700px;" >

In [40]:
# Pythonic Way
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print("x:"+" shape: "+ str(x.shape))
print(x)
print("\nv:"+" shape: "+ str(v.shape))
print(v)

print("\ny:"+" shape: "+ str(y.shape))
print(y)

x: shape: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

v: shape: (3,)
[1 0 1]

y: shape: (4, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [41]:
#Using Broadcast

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting

print("x:"+" shape: "+ str(x.shape))
print(x)
print("\nv:"+" shape: "+ str(v.shape))
print(v)
print("\ny:"+" shape: "+ str(y.shape))
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

x: shape: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

v: shape: (3,)
[1 0 1]

y: shape: (4, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [42]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print("v:"+" shape: "+ str(v.shape))
print(v)
print("\nw:"+" shape: "+ str(w.shape))
print(w)

print("Reshaped:")
print(v.reshape(3,1))

print("\nOuter Product Based on Broadcasting")
print(np.reshape(v, (3, 1)) * w)
print("\nOuter Product")
print(np.dot(v.reshape(3,1), w.reshape(1,2)))

# Add a vector to each row of a matrix



v: shape: (3,)
[1 2 3]

w: shape: (2,)
[4 5]
Reshaped:
[[1]
 [2]
 [3]]

Outer Product Based on Broadcasting
[[ 4  5]
 [ 8 10]
 [12 15]]

Outer Product
[[ 4  5]
 [ 8 10]
 [12 15]]


In [43]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
x = np.array([[1,2,3], [3,5,7]])
print("x:"+" shape: "+ str(x.shape))
print(x)
print("\nw:"+" shape: "+ str(w.shape))
print(w)
print "\n(x.T + w).T"
print((x.T + w).T)

print "\n(x + w.reshape(2,1)"
print((x + w.reshape(2,1)))


x: shape: (2, 3)
[[1 2 3]
 [3 5 7]]

w: shape: (2,)
[4 5]

(x.T + w).T
[[ 5  6  7]
 [ 8 10 12]]

(x + w.reshape(2,1)
[[ 5  6  7]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

Refer to numpy cheat-sheet during usage

# Examples

## $l_2 \ norm $

### $$ \left | \left | X- Y \right | \right |^{2}_{2} \ \  \ \    X, Y \in m \times n$$

In [44]:
import numpy.linalg as LA

X= np.random.random((3,3))
Y= np.random.random((3,3))
print(X)
print("")
l2_norm = LA.norm(X-Y)
print l2_norm

[[ 0.60825878  0.89538017  0.91479214]
 [ 0.58138762  0.30194153  0.53107794]
 [ 0.82471896  0.68840443  0.13799856]]

1.35144941541


In [45]:
l2_norm = np.sqrt( np.sum((X - Y)**2) )
print l2_norm

1.35144941541


## Evaluate LA Expression

### $$ q= (z^{T} \ast (\frac{1}{2}x^{T}A + c^{T}A)  )_{+} \ \ \ \ \ \ \ \scriptsize + \  denotes \ \  max(0,X_{ij}) $$
### $$x,c,z \in m \times 1, \ A \in m \times m $$


In [46]:
m =3
A = np.float64(np.random.randint(-5,10, (m,m)))
x = np.float64(np.random.randint(-5,7, (m,1)))
c = np.float64(np.random.randint(-5,5, (m,1)))
z = np.float64(np.random.randint(-5,5, (m,1)))

print ("A:")
print(A)

q = z.T*( ((1.0/2)* (x.T.dot(A)) )  + (c.T.dot(A)))

print("")
print(q)
print("")

q[q<0] = 0
print(q)


A:
[[ 8. -2.  3.]
 [ 3.  5.  7.]
 [ 6.  7. -2.]]

[[ 61.5 -72.    3. ]]

[[ 61.5   0.    3. ]]


## Nearest Neighbors

### $$ D_{ij}^{2} = (x_i - x_j)^{2} + (y_{i} - y_{j})^{2} $$ 

Naive Approach requires three nested loops

In [47]:
x= np.float64(np.random.randint(0, 5,(4,3) ))
x.shape

(4, 3)

In [48]:
x

array([[ 4.,  0.,  3.],
       [ 2.,  2.,  4.],
       [ 2.,  0.,  0.],
       [ 0.,  3.,  0.]])

In [49]:
x.reshape(4,1,3)

array([[[ 4.,  0.,  3.]],

       [[ 2.,  2.,  4.]],

       [[ 2.,  0.,  0.]],

       [[ 0.,  3.,  0.]]])

In [50]:
diff = x.reshape(4,1,3) - x
diff.shape

(4, 4, 3)

In [51]:
diff

array([[[ 0.,  0.,  0.],
        [ 2., -2., -1.],
        [ 2.,  0.,  3.],
        [ 4., -3.,  3.]],

       [[-2.,  2.,  1.],
        [ 0.,  0.,  0.],
        [ 0.,  2.,  4.],
        [ 2., -1.,  4.]],

       [[-2.,  0., -3.],
        [ 0., -2., -4.],
        [ 0.,  0.,  0.],
        [ 2., -3.,  0.]],

       [[-4.,  3., -3.],
        [-2.,  1., -4.],
        [-2.,  3.,  0.],
        [ 0.,  0.,  0.]]])

In [52]:
D = np.sum(np.square(diff), axis=2)
D.shape

(4, 4)

In [53]:
D

array([[  0.,   9.,  13.,  34.],
       [  9.,   0.,  20.,  21.],
       [ 13.,  20.,   0.,  13.],
       [ 34.,  21.,  13.,   0.]])

In [54]:
i= np.arange(4)
D[i,i] = np.inf
D

array([[ inf,   9.,  13.,  34.],
       [  9.,  inf,  20.,  21.],
       [ 13.,  20.,  inf,  13.],
       [ 34.,  21.,  13.,  inf]])

In [55]:
j = np.argmin(D,1)
j[:], j.shape

(array([1, 0, 0, 2]), (4,))

#### Compiling the above

In [56]:
x= np.float64(np.random.randint(0, 100,(1000,3) ))
diff = x.reshape(1000,1,3) - x
D = np.sum(np.square(diff), axis=2)
i= np.arange(1000)
D[i,i] = np.inf
j = np.argmin(D,1)
j[:10], j.shape

(array([921, 150, 674, 655, 919,  15, 541, 814, 143, 851]), (1000,))