In [19]:
import numpy as np
from collections import defaultdict

In [20]:
# Helper function to print a fuzzy membership function
# The function prints the membership function in the following way:-
# { 0.1/1 0.2/2 0.3/3 }

def print_fuzzy(D):
    print('{ ', end='')
    for keys in D.keys():
        print(str(D[keys]) + "/" + str(keys) + " ", end='')
    print('}')   

## 1. Bold Intersection

Bold Intersection is defined as:-  
µAoB(x) = Max [0, µA(x) + µB(x) - 1]

### Question 1: 
Compute AoB, where   
A = { 0.4/1, 0.9/2, 0.9/3, 1/4 }  
B = { 0.9/1, 0.5/2, 0.8/3  }  
X = {1, 2, 3, 4} Universe of Discourse

In [43]:
def fuzzy_bold_intersection(A, B):
    # A and B are dictionaries whose keys are integers and whose values are the degrees of membership of the integers.
    # Compute the Bold Intersection of A and B store it in a new dictionary fuzz_bu.
    fuzz_bu = {}
    keys = set.intersection(set(A.keys()), set(B.keys()))
    for key in keys:
        #To prevent zero values
        if round(max(0, A[key] + B[key] - 1), 2) != 0:
            fuzz_bu[key] = round(max(0, A[key] + B[key] - 1), 2)
    return fuzz_bu

# Create dictionary A
A = {1:0.4, 2:0.9, 3:0.9, 4:1}
# Create dictionary B
B = {1:0.9, 2:0.5, 3:0.8}
print_fuzzy(fuzzy_bold_intersection(A,B))

{ 0.3/1 0.4/2 0.7/3 }


## 2. Complement

Complement is defined as:-  
µA’(x) =  [1 - µA(x) ], x belongs to X,  
where X is the Universe of Discourse

### Question 2:  
Compute C complement  
C = { 0.2/1, 0.9/3, 0.5/4 }  
X = {1, 2, 3, 4} Universe of Discourse



In [44]:
def fuzzy_complement(C, X):
    # C is a dictionary whose keys are integers and whose values are the degrees of membership of the integers.
    # Compute the Complement of C store it in a new dictionary fuzz_comp.
    fuzz_comp = {}
    for x in X:
        if x in C:
            #To prevent 0 values
            if C[x] is not 1:
                fuzz_comp[x] = round(1 - C[x], 2)
        else:
            fuzz_comp[x] = 1
    return fuzz_comp

# Create fuzzy set C
C = {1:0.2, 3:0.9, 4:0.5}
X = [1, 2, 3, 4]

print_fuzzy(fuzzy_complement(C, X))

{ 0.8/1 1/2 0.1/3 0.5/4 }


## 3. Addition

+ Consider all possible pairs (x,y) such that x belongs to A and y belongs to B. 
+ Each pair gives rise to a new element in the set(A+B) whose value is (x+y) and corresponding membership degree is min(µA(x), µB(y)). 
+ Next eliminate all the repeating values in the set(A+B) by picking the maximum membership degree among all membership degrees for a particular value.  

Here is an example:-

A = 0.3/1 + 0.6/2 + 1/3 + 0.7/4 + 0.2/5  
B = 0.5/10 + 1/11 + 0.5/12

(A + B) = 0.3/11 + 0.5/12 + 0.5/13 + 0.5/14 + 0.2/15 + 0.3/12 + 0.6/13+1/14 + 0.7/15 + 0.2/16 + 0.3/13 + 0.5/14 + 0.5/15 + 0.5/16 + 0.2/17  

Get the max of the duplicates, so we get,  
(A + B) = (0.3/11) + 0.5/12 + 0.6/13 + 1/14 + 0.7/15 + 0.5/16 + 0.2/17

## 4. Addition Modified:-

Define a function 'fuzzy_add_mod' which takes in 3 membership functions A,B and C.  
Modified add is defined as follows:-  
µ(A,B,C) =  µ(AoB) +  µC'

### Question 3: 
Compute Add_modified(A,B,C)   
Use A,B and C from questions 1 and 2


In [46]:
def fuzzy_add_mod(A,B,C):
    # A,B and C are dictionaries whose keys are integers and whose values are the degrees of membership of the integers.
    # Compute the Modified Sum of A, B and C and store it in a new dictionary fuzz_sum.
    D = fuzzy_bold_intersection(A, B)
    # This gives a default value of 0 for all keys of the dictionary which don't already exist
    fuzz_sum = defaultdict(lambda: 0)
    for key1 in D.keys():
        for key2 in C.keys():
            fuzz_sum[key1 + key2] = max(min(D[key1],C[key2]), fuzz_sum[key1 + key2])
    return fuzz_sum 
    
print_fuzzy(fuzzy_add_mod(A,B,C))

{ 0.2/2 0.2/3 0.3/4 0.4/5 0.7/6 0.5/7 }


# 4. Fuzzy Relations

Let's define a fuzzy relation for the statement, "If test is tough, marks are scored".

We can have 2 fuzzy sets for toughness of a test and scores in the test. Assume toughness on a scale of 1 to 5 and marks from 0 to 10.

A = 0.3/1 + 0.4/2 + 0.7/3 + 0.5/4 + 0.2/5

B = 0.1/0 + 0.3/1 + 0.5/2 + 0.7/3 + 0.8/4 + 0.9/5 + 0.8/6 + 0.7/7 + 0.5/8 + 0.3/9 + 0.1/10

The fuzzy relation can be calculated by computing the minimum of µA(x) and µB(y) for each µR(x, y). This would give us:

µR(x, y) = [ 0.1  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.1   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.1  0.3  0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.3  0.1   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.1  0.3  0.5  0.7  0.7  0.7  0.7  0.7  0.5  0.3  0.1   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.1  0.3  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.3  0.1   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.1  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.1 ]
             

In [31]:
def fuzzy_if(A, B):
    # A and B are dictionaries whose keys are integers and whose values are the degrees of membership of the integers.
    # Compute the fuzzy relation of A and B and store it in a new matrix fuzz_rel.
    fuzz_rel = np.zeros((len(A.keys()), len(B.keys())))
    for i, key1 in enumerate(A.keys()):
        for j, key2 in enumerate(B.keys()):
            fuzz_rel[i][j] = min(A[key1], B[key2])
    return fuzz_rel
    
# Create fuzzy set A for toughness
A = {1:0.3, 2:0.4, 3:0.7, 4:0.5, 5:0.2}
# Create fuzzy set B for scores
B = {0:0.1, 1:0.3, 2:0.5, 3:0.7, 4:0.8, 5:0.9, 6:0.8, 7:0.7, 8:0.5, 9:0.3, 10:0.1}

print(fuzzy_if(A, B))

[[ 0.1  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.1]
 [ 0.1  0.3  0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.3  0.1]
 [ 0.1  0.3  0.5  0.7  0.7  0.7  0.7  0.7  0.5  0.3  0.1]
 [ 0.1  0.3  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.3  0.1]
 [ 0.1  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.1]]


### Composite relation
 We can define another to relate toughness with the preparedness for the test.
 
 Let preparedness be on a scale of 1 to 5:
 
 C = 0.2/1 + 0.3/2 + 0.5/3 + 0.7/4 + 0.2/5
 
 We can now define two relations from A to B and from B to C to relate A to C. We will use the min-max method to do the same.

In [47]:
def fuzzy_comp(A, B):
    # A and B are relations.
    # Compute the fuzzy composition of A and B and store it in a new matrix fuzz_rel.
    
    #We use 1's as we would apply the min operation on it later
    fuzz_rel = np.ones((np.shape(A)[0], np.shape(B)[1]))
    #The loops for i, j, k can be shuffled around as most convenient
    for i in range(0, np.shape(A)[0]):
        for j in range(0, np.shape(B)[1]):
            for k in range(0, np.shape(A)[1]):
                fuzz_rel[i][j] = min(fuzz_rel[i][j], max(A[i][k], B[k][j]))
    return fuzz_rel
    
# Create fuzzy set C for preparedness
C = {1:0.2, 2:0.3, 3:0.5, 4:0.7, 5:0.2}
# Create fuzzy relation R1 for toughness to scores
R1 = fuzzy_if(A, B)
# Create fuzzy relation R2 for scores to preparedness
R2 = fuzzy_if(B, C)

print(fuzzy_comp(R1, R2))

[[ 0.4  0.4  0.5  0.5  0.4]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5]]
